# Generated by Django 5.2.8 on 2026-03-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
