# Generated by Django 5.2.8 on 2026-03-03 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_groupbuy_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
