# Generated by Django 5.2.8 on 2026-03-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_groupbuy_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbuy',
            name='end_time',
        ),
    ]
